spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ordermesh}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate.ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
